sonar.projectKey=Warj-Group_API5BD2026ETL
sonar.organization=warj-group
sonar.python.version=3.11
sonar.sources=.
sonar.language=py
sonar.exclusions=**/tests/**, **/migrations/**, **/venv/**, **/.env/**, **/__pycache__/**, **/*.pyc
sonar.coverage.exclusions=**/*

# Sem cobertura de código, apenas: bugs, vulnerabilidades e code smells
# sonar.python.coverage.reportPaths=coverage.xml
# - name: Run Tests and Generate Coverage
#   run: |
#     pip install pytest pytest-cov
#     pytest --cov=. --cov-report=xml  # Isso cria o arquivo coverage.xml