# Identificação Obrigatória
sonar.projectKey=Warj-Group_API5BD2026ETL
sonar.organization=warj-group

# Configurações do Projeto
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10

# Exclusões importantíssimas para Python
sonar.exclusions=**/venv/**, **/.env/**, **/__pycache__/**, **/*.pyc